name: Build Release Page
description: Creates a md page that contains the release information of a Github release

inputs:
  organization:
    required: true
    description: The Organization that hosts the Repo that holds the Release
  repository:
    required: true
    description: The Repository that holds the Release
  release:
    required: true
    description: The tag name of the release

runs:
  using: "composite"
  steps:

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - shell: bash
      run: |
        pip3 install -r ${{ github.action_path }}/requirements.txt
        python3 ${{ github.action_path }}/build_release_page.py ${{ inputs.organization }} ${{ inputs.repository }} ${{ inputs.release }}

